server:
  servlet:
    context-path: /api
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/matcha
    driver-class-name: org.postgresql.Driver
    username: test
    password: test
logging:
  level:
    org.springframework:
      jdbc:
        core:
          JdbcTemplate: debug
token:
  jwtSecret: matchaSecretKey
  jwtExpirationMs: 3600000
  jwtRefreshExpirationMs: 86400000