server:
  port: 8081
  servlet:
    context-path: /jwt
spring:
  profiles:
    active: @activatedProperties@
  application:
    name: access
token:
  jwtSecret: matchaSecretKey
  jwtExpirationMs: 3600000