server:
  servlet:
    context-path: /api
  error:
    include-message: always
  port: 80
spring:
  profiles:
    active: @activatedProperties@
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5433/matcha
    driver-class-name: org.postgresql.Driver
    username: test
    password: test
logging:
  level:
    org.springframework:
      jdbc:
        core:
          JdbcTemplate: debug
token:
  jwtRefreshExpirationMs: 86400000

matcha:
  access:
    url: http://localhost:81/access